blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # path('', views.post_list, name='post_list'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', 
         views.post_detail, 
         name='post_detail'
         ),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('subscribe/', views.subscribe, name='subscribe'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('captcha/', include('captcha.urls')),
]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.urls import reverse
# from django.db.models.functions import Now

# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return (super().get_queryset().filter(status=Post.Status.PUBLISHED))
    
class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'PUBLISHED'
        
    title = models.CharField(max_length=250)
    slug = models.SlugField(
        max_length=250,
        unique_for_date='publish'
        )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='blog_posts'
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=2,
        choices=Status,
        default=Status.DRAFT
    )
    # publish = models.DateTimeField(db_default=Now())

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse(
            'blog:post_detail',
            args=[
                self.publish.year,
                self.publish.month,
                self.publish.day,
                self.slug,
            ]
        )

class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    name = models.CharField(max_length=25)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['created'])
        ]

        def __str__(self):
            return f"Comment by {self.name} on {self.post}"
        
class Subscriber(models.Model):
    email = models.EmailField(unique=True)
    subscribed_at = models.DateTimeField(auto_now_add=True)

blog/forms.py
from django import forms
from .models import Comment, Subscriber
from captcha.fields import CaptchaField

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(
        required=False,
        widget=forms.Textarea
    )
    captcha = CaptchaField()

class CommentForm(forms.ModelForm):
    captcha = CaptchaField()
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

class SubscribeForm(forms.ModelForm):
    class Meta:
        model = Subscriber
        fields = ['email']

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.http import Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.http import require_POST
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail

# Create your views here.

class PostListView(ListView):

    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 7
    template_name = 'blog/post/list.html'

def post_list(request):
    post_list = Post.published.all()

    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page', 1)

    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(
        request,
        'blog/post/list.html',
        {'posts': posts}
    )

# def post_detail(request, id):
#     try:
#         post = Post.published.get(id=id)
#     except Post.DoesNotExist:
#         raise Http404("No Post Found")
#     return render(
#         request,
#         'blog/post/detail.html',
#         {'post': post}
#     )

def post_detail(request, year, month, day, post):
    post = get_object_or_404(
        Post,
        status=Post.Status.PUBLISHED,
        slug=post,
        publish__year=year,
        publish__month=month,
        publish__day=day,
    )

    comments = post.comments.filter(active=True)

    form = CommentForm()
    

    return render(
        request,
        'blog/post/detail.html',
        {
            'post': post,
            'form': form,
            'comments': comments,
            }
    )

def post_share(request, post_id):
    post = get_object_or_404(
        Post,
        id=post_id,
        status=Post.Status.PUBLISHED
    )
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url()
            )

            subject = (
                f"{cd['name']} ({cd['email']}) "
                f"recommends you read {post.title}"
            )
            message=(
                f"Read {post.title} at {post_url}\n\n"
                f"{cd['name']}\'s comments: {cd['comments']}"
            )

            send_mail(
                subject=subject,
                message=message,
                from_email=None,
                recipient_list=[cd['to']]
            )
            sent = True
        
    else:
        form = EmailPostForm()

    return render(
        request,
        'blog/post/share.html',
        {
            'post': post,
            'form': form,
            'sent': sent,
        }
        )

@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(
        Post,
        id=post_id,
        status=Post.Status.PUBLISHED,
    )
    comment = None

    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)

        comment.post = post

        comment.save()

    return render(
        request,
        'blog/post/comment.html',
        {
            'post': post,
            'form': form,
            'comment': comment,
        }
    )

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %} {% endblock %}</title>
        <!-- <link rel="stylesheet" href="https://unpkg.com/mvp.css">  -->
        <!-- <link rel="stylesheet" href="https://unpkg.com/sakura.css/css/sakura.css" type="text/css"> -->
        <link rel="stylesheet" href="https://cdn.simplecss.org/simple.css">
        <link rel="icon" type=”image/x-icon” href="{% static 'images/favicon.ico' %}">
        <!-- <link rel="stylesheet" href="{% static 'css/blog.css' %}"> -->
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>

    <body>
        <header>
            <nav>
                <a href="{% url 'blog:post_list' %}">Home</a>
                <a href="https://github.com/eniolakunle/DjangoBlog">GitHub</a>
            </nav>
            <hgroup>
                <h1>The Secret Place</h1>
                <p>
                    Daily Insights of The Word! 
                    <br>
                    <sub>(With the Help of ChatGPT)</sub>
                </p>
            </hgroup>
        </header>
        
        <div id="content">
            {% block content %}
            {% endblock %}
        </div>
        <footer id="sidebar">
            <h6>
                <div id="dailyVersesWrapper"></div>
            </h6>
            <img src="{% static 'images/jeezus.jpg' %}" alt="The Christ" id="jesusimg">
        </footer>
        <script async defer src="https://dailyverses.net/get/random.js?language=esv"></script>
    </body>
</html>

blog/templates/blog/includes/subscribe_form.html
<form action="{% url 'blog:subscribe' %}" method="post">
    <input type="email" name="email" placeholder="abc@xyz.com" id="user_email" required>
    {% csrf_token %}
    <button type="submit">Subscribe</button>
</form>

blog/templates/blog/post/comment.html
{% extends "blog/base.html" %}

{% block title %} Add a comment {% endblock %}

{% block content %}
    {% if comment %}
        <h2>Your comment has been added!</h2>
        <p>
            <a href="{{ post.get_absolute_url }}">Back to the post</a>
        </p>
    {% else %}
        {% include "blog/post/includes/comment_form.html" %}
    {% endif %}
{% endblock %}

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %} {{post.title}} {% endblock %}

{% block content %}

    <h1>
        {{post.title}}
    </h1>
    <small class="date">
        Published {{post.publish}} by {{post.author}}
    </small>
    <br>
    <small class="date">
        Updated on {{post.updated}}
    </small>
    <hr>
    {{ post.body|linebreaks }}
    <p>
        <a href="{% url 'blog:post_share' post.id %}">
            <button>Share this post</button>
        </a>
    </p>
    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}
    {% for comment in comments %}
        <blockquote class="comment">
            <small class="info">
                Comment {{ forloop.counter }} by {{comment.name}}
                {{comment.created}}
            </small>
            <br>
            {{ comment.body }}
        </blockquote>
    {% empty %}
        <p>👇What do you think? Leave a comment below!👇 </p>
    {% endfor %}
    {% include "blog/post/includes/comment_form.html" %}
{% endblock %}

blog/templates/blog/post/includes/comment_form.html
<h2>Add a comment</h2>
<form action="{% url 'blog:post_comment' post.id %}" method="post">
    <div class="left">
        {{ form.name.as_field_group }}
    </div>
    <div class="left">
        {{ form.email.as_field_group }}
    </div>
    <!-- {{ form.as_p }} -->
      {{ form.body.as_field_group }}
      {{ form.captcha.as_field_group }}
    {% csrf_token %}
    <p>
        <input type="submit" value="Add a comment">
    </p>
</form>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}The Secret Place{% endblock %}

{% block content %}
    <!-- <h1>Jesus Blog</h1> -->
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{post.title}}
            </a>
        </h2>
        <article>
        <small class ="date">
            Published {{post.publish}} by {{post.author}}
            <br>
            <!-- {{post.comments.count}} comment{{post.comments.count|pluralize}} -->
        </small>
    {{ post.body|truncatewords:30|linebreaks }}
</article>
{% endfor %}
{% include "blog/post/pagination.html" with page=page_obj %}
{% endblock %}

blog/templates/blog/post/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number}} of {{page.paginator.num_pages }}
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %} Share a post {% endblock %}

{% block content %}
    {% if sent %}
        <h1>Email successfully sent</h1>
        <p>
            "{{post.title}}" was succesfully sent to {{form.cleaned_data.to}}.
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by email</h1>
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
                <input type="submit" value="Send email">
        </form>
    {% endif %}
{% endblock %}

blog/templates/blog/subscribe.html
{% extends "blog/base.html" %}

{% block title %} Confirm Subscription {% endblock %}

{% block content %}
        <hgroup>
                <h2>Please check your email to confirm your subscription!</h2>
                <p>Let's confirm that <b>{{ form.email.value }}</b> is your email and we're good to go.</p>
        </hgroup>
{% endblock %}